spring.application.name=finance


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=postgres
spring.datasource.password=Yash@123

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secretKey=dfj38f4un2id6HD#6y3nl23879HSND3726tJDKHJ#^#f4896@#Hd9673jhf&@